apiVersion: v1
items:
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: '1'
      creationTimestamp: 2017-07-07T18:51:59Z
      generation: 1
      labels:
        io.kompose.service: hdderive
      name: hdderive
      namespace: default
      resourceVersion: '3439527'
      selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/hdderive
      uid: 5b3ffc2f-6345-11e7-8167-42010a800254
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: hdderive
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            io.kompose.service: hdderive
        spec:
          volumes:          
          containers:
            - env:
              image: us.gcr.io/multichain-prod/hdderive
              imagePullPolicy: Always
              name: hdderive
              ports:
                - containerPort: 3000
                  protocol: TCP
              resources: {}
              stdin: true
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              tty: true
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
    status:
      conditions:
        - lastTransitionTime: 2017-07-07T18:51:59Z
          lastUpdateTime: 2017-07-07T18:51:59Z
          message: Deployment has minimum availability.
          reason: MinimumReplicasAvailable
          status: 'True'
          type: Available
      observedGeneration: 1
      replicas: 1
      unavailableReplicas: 1
      updatedReplicas: 1
kind: List
metadata: {}
resourceVersion: ''
selfLink: ''
